// ============================================
// PDF Invoice Generator Utility
// ============================================

import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

/**
 * Generates a professional PDF Invoice for a Sale or Purchase.
 *
 * @param {Object} data  - Transaction data including items, totals, party info
 * @param {string} type  - 'SALE' or 'PURCHASE'
 * @param {Array}  productMap - Optional array of {id, name} to resolve product names
 */
export const generateInvoicePDF = (data, type = 'SALE', productMap = []) => {
    const doc = new jsPDF();
    const isSale = type === 'SALE';
    const primaryColor = [10, 107, 233]; // Vyaparisetu Blue

    // Build a lookup map for product names so we can resolve UUIDs → names
    // FIX: Previously the PDF showed raw UUIDs instead of product names because
    // item.productName was never set in the form state. Now we accept an optional
    // productMap (array of {id, name}) from the caller, and fall back to the
    // product name by looking up by ID.
    const productNameMap = {};
    for (const p of productMap) {
        productNameMap[p.id] = p.name;
    }

    // ─── Header ──────────────────────────────────
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text(isSale ? 'TAX INVOICE' : 'PURCHASE ORDER', 15, 25);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Date: ${new Date(data.date || Date.now()).toLocaleDateString()}`, 160, 20);
    doc.text(`Invoice #: ${data.invoiceNumber || 'DRAFT'}`, 160, 26);

    // ─── Party Details ────────────────────────────
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(10);
    doc.text(isSale ? 'BILL TO:' : 'SUPPLIER:', 15, 55);
    doc.setFont('helvetica', 'bold');
    doc.text(data.partyName || (isSale ? 'Walk-in Customer' : 'Unknown Supplier'), 15, 62);
    doc.setFont('helvetica', 'normal');
    if (data.mobile) doc.text(`Phone: ${data.mobile}`, 15, 68);

    // ─── Items Table ─────────────────────────────
    const tableColumn = ['Product', 'Quantity', 'Rate', 'Tax %', 'Total'];
    const tableRows = (data.items || []).map(item => [
        // FIX: Resolve product name using the lookup map first,
        // then fall back to item.productName, then to 'Unknown (short UUID)'
        productNameMap[item.productId]
        || item.productName
        || (item.productId ? `Product (${String(item.productId).slice(0, 8)}...)` : 'Unknown Product'),
        `${item.quantity} ${item.unit || 'pcs'}`,
        `Rs. ${Number(item.unitPrice).toFixed(2)}`,
        `${item.gstRate || 0}%`,
        `Rs. ${Number(item.total).toFixed(2)}`
    ]);

    doc.autoTable({
        startY: 80,
        head: [tableColumn],
        body: tableRows,
        theme: 'striped',
        headStyles: { fillColor: primaryColor, textColor: 255 },
        footStyles: { fillColor: [240, 240, 240], textColor: 0, fontStyle: 'bold' },
        styles: { fontSize: 9, cellPadding: 4 },
        columnStyles: { 4: { halign: 'right' } }
    });

    // ─── Summary ──────────────────────────────────
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFont('helvetica', 'bold');
    doc.text(`Subtotal:`, 140, finalY);
    doc.text(`Rs. ${data.subtotal?.toFixed(2) || '0.00'}`, 190, finalY, { align: 'right' });

    doc.text(`Total GST:`, 140, finalY + 7);
    doc.text(`Rs. ${data.tax?.toFixed(2) || '0.00'}`, 190, finalY + 7, { align: 'right' });

    doc.setFontSize(14);
    doc.setTextColor(...primaryColor);
    doc.text(`Grand Total:`, 140, finalY + 18);
    doc.text(`Rs. ${data.total?.toFixed(2) || '0.00'}`, 190, finalY + 18, { align: 'right' });

    // ─── Footer ───────────────────────────────────
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Vyaparisetu - Intelligent Business Operating System', 105, 285, { align: 'center' });

    // ─── Download ─────────────────────────────────
    doc.save(`Invoice_${data.invoiceNumber || 'Draft'}.pdf`);
};
