// ============================================
// PDF Invoice Generator Utility
// ============================================

import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

/**
 * Generates a professional PDF Invoice for a Sale or Purchase
 */
export const generateInvoicePDF = (data, type = 'SALE') => {
    const doc = jsPDF();
    const isSale = type === 'SALE';
    const primaryColor = [10, 107, 233]; // Vyaparisetu Blue

    // ─── Header ──────────────────────────────────
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text(isSale ? 'TAX INVOICE' : 'PURCHASE ORDER', 15, 25);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Date: ${new Date(data.date).toLocaleDateString()}`, 160, 20);
    doc.text(`Invoice #: ${data.invoiceNumber || 'DRAFT'}`, 160, 26);

    // ─── Party Details ────────────────────────────
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(10);
    doc.text(isSale ? 'BILL TO:' : 'SUPPLIER:', 15, 55);
    doc.setFont('helvetica', 'bold');
    doc.text(data.partyName || 'Walk-in Customer', 15, 62);
    doc.setFont('helvetica', 'normal');
    if (data.mobile) doc.text(`Phone: ${data.mobile}`, 15, 68);

    // ─── Items Table ─────────────────────────────
    const tableColumn = ["Product", "Quantity", "Rate", "Tax %", "Total"];
    const tableRows = (data.items || []).map(item => [
        item.productName || item.productId,
        `${item.quantity} ${item.unit}`,
        `Rs. ${Number(item.unitPrice).toFixed(2)}`,
        `${item.gstRate}%`,
        `Rs. ${Number(item.total).toFixed(2)}`
    ]);

    doc.autoTable({
        startY: 80,
        head: [tableColumn],
        body: tableRows,
        theme: 'striped',
        headStyles: { fillColor: primaryColor, textColor: 255 },
        footStyles: { fillColor: [240, 240, 240], textColor: 0, fontStyle: 'bold' },
        styles: { fontSize: 9, cellPadding: 4 },
        columnStyles: {
            4: { halign: 'right' }
        }
    });

    // ─── Summary ──────────────────────────────────
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFont('helvetica', 'bold');
    doc.text(`Subtotal:`, 140, finalY);
    doc.text(`Rs. ${data.subtotal?.toFixed(2) || '0.00'}`, 190, finalY, { align: 'right' });

    doc.text(`Total GST:`, 140, finalY + 7);
    doc.text(`Rs. ${data.tax?.toFixed(2) || '0.00'}`, 190, finalY + 7, { align: 'right' });

    doc.setFontSize(14);
    doc.setTextColor(...primaryColor);
    doc.text(`Grand Total:`, 140, finalY + 18);
    doc.text(`Rs. ${data.total?.toFixed(2) || '0.00'}`, 190, finalY + 18, { align: 'right' });

    // ─── Footer ───────────────────────────────────
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    const footerText = "Generated by Vyaparisetu - Intelligent Business Operating System";
    doc.text(footerText, 105, 285, { align: 'center' });

    // Save/Download
    doc.save(`Invoice_${data.invoiceNumber || 'Draft'}.pdf`);
};
